// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeamoSharp.DataAccessLayer;

namespace TeamoSharp.DataAccessLayer.Migrations
{
    [DbContext(typeof(TeamoContext))]
    [Migration("20200324183951_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("TeamoSharp.DataAccessLayer.Models.ClientMessage", b =>
                {
                    b.Property<int>("ClientMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChannelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PostId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServerId")
                        .HasColumnType("TEXT");

                    b.HasKey("ClientMessageId");

                    b.HasIndex("PostId")
                        .IsUnique();

                    b.ToTable("ClientMessage");
                });

            modelBuilder.Entity("TeamoSharp.DataAccessLayer.Models.Member", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumPlayers")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PostId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MemberId");

                    b.HasIndex("PostId");

                    b.ToTable("Member");
                });

            modelBuilder.Entity("TeamoSharp.DataAccessLayer.Models.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Game")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("INTEGER");

                    b.HasKey("PostId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("TeamoSharp.DataAccessLayer.Models.ClientMessage", b =>
                {
                    b.HasOne("TeamoSharp.DataAccessLayer.Models.Post", null)
                        .WithOne("Message")
                        .HasForeignKey("TeamoSharp.DataAccessLayer.Models.ClientMessage", "PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TeamoSharp.DataAccessLayer.Models.Member", b =>
                {
                    b.HasOne("TeamoSharp.DataAccessLayer.Models.Post", null)
                        .WithMany("Members")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
