// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeamoSharp.Models;

namespace TeamoSharp.Migrations
{
    [DbContext(typeof(PlayContext))]
    partial class PlayContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2");

            modelBuilder.Entity("TeamoSharp.Models.PlayMember", b =>
                {
                    b.Property<int>("PlayMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("DiscordUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumPlayers")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlayPostId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayMemberId");

                    b.HasIndex("PlayPostId");

                    b.ToTable("PlayMember");
                });

            modelBuilder.Entity("TeamoSharp.Models.PlayPost", b =>
                {
                    b.Property<int>("PlayPostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("DiscordChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DiscordMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Game")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayPostId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("TeamoSharp.Models.PlayMember", b =>
                {
                    b.HasOne("TeamoSharp.Models.PlayPost", null)
                        .WithMany("Members")
                        .HasForeignKey("PlayPostId");
                });
#pragma warning restore 612, 618
        }
    }
}
